### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by lbrendanl** [space-dust-blockchain/eth-plot#1]
- [ ] (Brendan) setup testnet on my machine and work on dynamic pricing feature.

- [ ] (Samm) rendering of test data in UI.

- [ ] FAQ Page

- [ ] My Plots page with info about what you own

- [ ] UI for updating your pieces for sale and setting prices

- [ ] UI for purchasing a new plot TBD
